mod

diff --git a/misc/curl_edit_item b/misc/curl_edit_item
--- a/misc/curl_edit_item
+++ b/misc/curl_edit_item
@@ -1,17 +1,96 @@
 #!/bin/sh
 
-url="https://admin.thebase.in/items/edit/4977347"
+if [ $# -lt 10 ]; then
+  echo "usage: $0 <id> <title> <detail> <price> <stock> <visible> <order_top> <variation> <variation_stock> <file>" >&2
+  exit
+fi
 
-agent='Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36'
+ifs=$IFS
 
+id=$1
+title=$2
+detail=$3
+price=$4
+stock=$5
+visible=$6
+order_top=$7
+variation=$8
+variation_stock=$9
+file=${10}
+
+form_url="https://admin.thebase.in/items/edit/$id"
+post_url="https://admin.thebase.in/items/edit/$id"
+
+# get token
+token=$(sh curl_token $form_url)
+set -- $token
+token_key=$1
+token_fields=$2
+
+# curl組み立て
 cmd=$(cat << EOC
-curl -G -v \
--A '$agent' \
-$url \
+curl -XPOST $post_url -v \
 -b cookie \
--c cookie
+-c cookie \
+ --data-urlencode 'data[Item][title]=$title' \
+ --data-urlencode 'data[Item][detail]=$detail' \
+ --data-urlencode 'data[Item][price]=$price' \
+ --data-urlencode 'data[Item][visible]=$visible' \
+ --data-urlencode 'data[Item][order_top]=$order_top' \
+ --data-urlencode '_method=POST' \
+ --data-urlencode 'data[_Token][key]=$token_key' \
+ --data-urlencode 'data[_Token][fields]=$token_fields' \
+ --data-urlencode 'data[_Token][unlocked]='
 EOC
 )
 
-# echo $cmd
+# curl variation項目
+if [ "$variation" = "" ]; then
+  cmd="$cmd --data-urlencode 'data[Item][stock]=$stock'"
+else
+  IFS=","
+  for v in $variation; do
+    IFS=$ifs
+    cmd="$cmd --data-urlencode 'data[Item][variation][]=$v'"
+    IFS=','
+  done
+  for v in $variation_stock; do
+    IFS=$ifs
+    cmd="$cmd --data-urlencode 'data[Item][variation_stock][]=$v'"
+    IFS=','
+  done
+  IFS=$ifs
+fi
+
+# curl file項目
+if [ "$file" != "" ]; then
+  json="{"
+  n=1
+  first=0
+  IFS=','
+  for f in $file; do
+    IFS=$ifs
+    # upload file
+    ret=$(curl_upload_image $f $n)
+    status=$(echo "$ret" | jq -r '.result_data.status')
+    if [ "$status" != "ok" ]; then
+      echo "failed upload file($f): $status $ret" >&2
+      exit 1
+    fi
+    src=$(echo "$ret" | jq -r '.result_data.src')
+    if [ $first -eq 0 ]; then
+      first=1
+    else
+      json="${json},"
+    fi
+    json="${json}\"${n}\":{\"order\":${n},\"src\":\"${src}\",\"status\":\"new\"}"
+    n=$(expr $n + 1)
+    IFS=','
+  done
+  IFS=$ifs
+  json="${json}}"
+  cmd="$cmd --data-urlencode 'data[Item][file_update]=$json'"
+fi
+
+#echo $cmd
 eval $cmd
